# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

#workspace = 1, class:firefox
#workspace = 2, class:kitty
#workspace = 3, class:Spotify
#workspace = 4, class:google-chrome

# Laptop display → Workspaces 1, 2, 3
workspace=4, monitor:eDP-1, default:true
workspace=5, monitor:eDP-1
workspace=6, monitor:eDP-1

# External display → Workspaces 4, 5, 6
workspace=1, monitor:HDMI-A-1, default:true
workspace=2, monitor:HDMI-A-1
workspace=3, monitor:HDMI-A-1

# Laptop screen workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3

# External monitor workspaces
bind = SUPER CTRL, 1, workspace, 4
bind = SUPER CTRL, 2, workspace, 5
bind = SUPER CTRL, 3, workspace, 6

