#!/bin/bash
# Full shell reload: quickshell + wallpaper + clipboard watchers

# Kill stale instances
killall ydotool qs quickshell wl-paste 2>/dev/null
sleep 0.5

# Restart quickshell (bar, launcher, widgets)
qs -c ii &

# Restore wallpaper (generated by switchwall.sh — may be empty on first boot)
bash "$HOME/.config/hypr/custom/scripts/__restore_video_wallpaper.sh" &

# Wait for qs to be ready, then restart clipboard watchers
sleep 2
wl-paste --type text  --watch bash -c 'cliphist store && qs -c ii ipc call cliphistService update' &
wl-paste --type image --watch bash -c 'cliphist store && qs -c ii ipc call cliphistService update' &
