#!/usr/bin/env bash
# Colour-theming companion for waypaper.
# Waypaper handles rendering; this script handles everything else:
#   - updates illogical-impulse config.json (wallpaperPath, thumbnailPath)
#   - regenerates __restore_video_wallpaper.sh so videos survive reboots
#   - runs the full Material You colour pipeline (matugen → terminal colours → GTK/Qt/Kitty)

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
ILLOGICAL_IMPULSE_VIRTUAL_ENV="${ILLOGICAL_IMPULSE_VIRTUAL_ENV:-$HOME/.local/state/quickshell/.venv}"

QUICKSHELL_CONFIG_NAME="ii"
SCRIPT_DIR="$XDG_CONFIG_HOME/quickshell/$QUICKSHELL_CONFIG_NAME/scripts/colors"
STATE_DIR="$XDG_STATE_HOME/quickshell"
SHELL_CONFIG_FILE="$XDG_CONFIG_HOME/illogical-impulse/config.json"
TERMSCHEME="$SCRIPT_DIR/terminal/scheme-base.json"
RESTORE_SCRIPT="$XDG_CONFIG_HOME/hypr/custom/scripts/__restore_video_wallpaper.sh"
THUMBNAIL_DIR="$XDG_CONFIG_HOME/hypr/custom/scripts/mpvpaper_thumbnails"
VIDEO_OPTS="loop panscan=1.0"

is_video() {
    local ext="${1##*.}"
    case "$ext" in mp4|webm|mkv|avi|mov|gif) return 0 ;; esac
    return 1
}

json_set() {
    jq --arg v "$2" "$1 = \$v" "$3" > "$3.tmp" && mv "$3.tmp" "$3"
}

imgpath=$(grep -m1 '^wallpaper\s*=' "$HOME/.config/waypaper/config.ini" \
    | cut -d'=' -f2- | xargs)
imgpath="${imgpath/#\~/$HOME}"

if [[ -z "$imgpath" || ! -f "$imgpath" ]]; then
    echo "[waypaper-apply] No valid wallpaper path, aborting." >&2
    exit 1
fi

mkdir -p "$STATE_DIR/user/generated"

if is_video "$imgpath"; then
    mkdir -p "$THUMBNAIL_DIR"
    thumbnail="$THUMBNAIL_DIR/$(basename "$imgpath").jpg"
    ffmpeg -y -i "$imgpath" -vframes 1 "$thumbnail" 2>/dev/null

    if [[ ! -f "$thumbnail" ]]; then
        echo "[waypaper-apply] ffmpeg failed to extract frame from $imgpath" >&2
        exit 1
    fi

    color_img="$thumbnail"
    json_set '.background.thumbnailPath' "$thumbnail" "$SHELL_CONFIG_FILE"

    cat > "$RESTORE_SCRIPT" << RESTORE
#!/bin/bash
# Generated by waypaper-apply.sh — do not edit manually.
pkill -f -9 mpvpaper || true
for monitor in \$(hyprctl monitors -j | jq -r '.[].name'); do
    mpvpaper -o "$VIDEO_OPTS" "\$monitor" "$imgpath" &
    sleep 0.1
done
RESTORE
    chmod +x "$RESTORE_SCRIPT"
else
    color_img="$imgpath"
    printf '#!/bin/bash\n# Generated by switchwall.sh - Don'\''t modify it by yourself.\n' \
        > "$RESTORE_SCRIPT"
fi

json_set '.background.wallpaperPath' "$imgpath" "$SHELL_CONFIG_FILE"

current_scheme=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null | tr -d "'")
[[ "$current_scheme" == "prefer-dark" ]] && mode="dark" || mode="light"

type_flag=$(jq -r '.appearance.palette.type' "$SHELL_CONFIG_FILE" 2>/dev/null)
if [[ -z "$type_flag" || "$type_flag" == "null" || "$type_flag" == "auto" ]]; then
    source "$ILLOGICAL_IMPULSE_VIRTUAL_ENV/bin/activate"
    detected=$("$SCRIPT_DIR/scheme_for_image.py" "$color_img" 2>/dev/null | tr -d '\n')
    deactivate
    valid_types="scheme-content scheme-expressive scheme-fidelity scheme-fruit-salad scheme-monochrome scheme-neutral scheme-rainbow scheme-tonal-spot"
    [[ " $valid_types " == *" $detected "* ]] && type_flag="$detected" || type_flag="scheme-tonal-spot"
fi

if [[ "$mode" == "dark" ]]; then
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
else
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
fi

enable_apps=$(jq -r '.appearance.wallpaperTheming.enableAppsAndShell' "$SHELL_CONFIG_FILE" 2>/dev/null)
[[ "$enable_apps" == "false" ]] && exit 0

harmony=$(jq -r '.appearance.wallpaperTheming.terminalGenerationProps.harmony' "$SHELL_CONFIG_FILE")
harmonize_threshold=$(jq -r '.appearance.wallpaperTheming.terminalGenerationProps.harmonizeThreshold' "$SHELL_CONFIG_FILE")
term_fg_boost=$(jq -r '.appearance.wallpaperTheming.terminalGenerationProps.termFgBoost' "$SHELL_CONFIG_FILE")
force_dark_terminal=$(jq -r '.appearance.wallpaperTheming.terminalGenerationProps.forceDarkMode' "$SHELL_CONFIG_FILE")
[[ "$force_dark_terminal" == "true" ]] && term_mode="dark" || term_mode="$mode"

matugen --source-color-index 0 image "$color_img" --mode "$mode" --type "$type_flag"

source "$ILLOGICAL_IMPULSE_VIRTUAL_ENV/bin/activate"
gen_args=(--path "$color_img" --mode "$term_mode" --scheme "$type_flag"
          --termscheme "$TERMSCHEME" --blend_bg_fg
          --cache "$STATE_DIR/user/generated/color.txt")
[[ "$harmony" != "null" && -n "$harmony" ]]                         && gen_args+=(--harmony "$harmony")
[[ "$harmonize_threshold" != "null" && -n "$harmonize_threshold" ]] && gen_args+=(--harmonize_threshold "$harmonize_threshold")
[[ "$term_fg_boost" != "null" && -n "$term_fg_boost" ]]             && gen_args+=(--term_fg_boost "$term_fg_boost")

python3 "$SCRIPT_DIR/generate_colors_material.py" "${gen_args[@]}" \
    > "$STATE_DIR/user/generated/material_colors.scss"
deactivate

"$SCRIPT_DIR/applycolor.sh"

kde_variant="$type_flag"
[[ ! " scheme-content scheme-expressive scheme-fidelity scheme-fruit-salad scheme-monochrome scheme-neutral scheme-rainbow scheme-tonal-spot " == *" $kde_variant "* ]] \
    && kde_variant="scheme-tonal-spot"
"$XDG_CONFIG_HOME/matugen/templates/kde/kde-material-you-colors-wrapper.sh" \
    --scheme-variant "$kde_variant" &
"$SCRIPT_DIR/code/material-code-set-color.sh" &
