-- Generated by nwg-displays on 2026-05-27 at 19:49:51. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@165.0",
    position = "3840x1080",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "3440x1440@59.97",
    position = "0x0",
    scale = 1.0
})
